// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en-US'

export type Locales =
	| 'en-US'
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * H​i​ ​{​n​a​m​e​}​!
	 * @param {string} name
	 */
	HI: RequiredParams<'name'>
	CMD_PING: {
		/**
		 * p​i​n​g
		 */
		name: string
		/**
		 * P​i​n​g​ ​t​h​e​ ​b​o​t
		 */
		description: string
	}
}

export type TranslationFunctions = {
	/**
	 * Hi {name}!
	 */
	HI: (arg: { name: string }) => LocalizedString
	CMD_PING: {
		/**
		 * ping
		 */
		name: () => LocalizedString
		/**
		 * Ping the bot
		 */
		description: () => LocalizedString
	}
}

export type Formatters = {}
